#!/usr/bin/env bash
# Usage: devenv whoami
# Summary: Print current profile

set -e

source $_DEVENV_ROOT/libs/profile.sh

active_profile="$(get_active_profile)"

if [[ "$active_profile" != "" ]]; then
  echo "$active_profile"
else
  cowsay <<EOF
"Through others we become ourselves."
― Lev S. Vygotsky
EOF
  echo "No profile loaded"
fi

# echo "# END"
