#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
# SCRIPT="$(readlink --canonicalize-existing "$0")"
# SCRIPTPATH="$(dirname "$SCRIPT")"
# SCRIPTNAME="$(basename "$SCRIPT")"
# Thanks https://dev.to/thiht/shell-scripts-matter :)

#/ Usage: devenv new [OPTIONS|--help] <profile name>
#/ Summary: Create a new developer environment profile
#/ Examples: :)
#/ Options:
#/   --help: Display this help message
#/   --version: Display programm version
#/ Version: 0.1.0
usage() { grep '^#/' "$0" | cut -c4- ; exit 0 ; }
version() { grep '^#/ Version:' "$0" | cut -c13- ; exit 0 ; }
expr "$*" : ".*--help" > /dev/null && usage
expr "$*" : ".*--version" > /dev/null && version

set -e

source "$_DEVENV_ROOT/libs/ui.sh"
source "$_DEVENV_ROOT/libs/profile.sh"

# cleanup() {}

# Parse command line options.
# while getopts m: OPT; do
# 	case "$OPT" in
# 	m)
# 		email=$OPTARG
# 		;;
# 	\?)
# 		# getopts issues an error message
# 		usage
# 		exit 1
# 		;;
# 	esac
# done
# Remove the switches we parsed above.
shift "$((OPTIND - 1))"

profile_name=$1
profile_folder=$PROFILE_PATHS/$profile_name

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    # trap cleanup EXIT
    __devenv_ui_header "Creating profile '$profile_name'"

    __devenv_profile_create "$profile_name" "$profile_folder"

    __devenv_plugin__aws__setup "$profile_folder"
    __devenv_plugin__bin__setup "$profile_folder"
    __devenv_plugin__envs__setup "$profile_folder"
    __devenv_plugin__gpg__setup "$profile_folder"
    __devenv_plugin__ssh__setup "$profile_folder"

    profile_config_folder="$profile_folder/.config"

    __devenv_plugin__aws__configure "$profile_config_folder"
    __devenv_plugin__email__configure "$profile_config_folder"
    __devenv_plugin__gpg__configure "$profile_config_folder"
    __devenv_plugin__ssh__configure "$profile_config_folder"

    devenv rehash "$profile_name"
    exit 0
fi
