#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
# SCRIPT="$(readlink --canonicalize-existing "$0")"
# SCRIPTPATH="$(dirname "$SCRIPT")"
# SCRIPTNAME="$(basename "$SCRIPT")"
# Thanks https://dev.to/thiht/shell-scripts-matter :)

#/ Usage: devenv new [OPTIONS|--help] <profile name>
#/ Summary: Create a new developer environment profile
#/ Examples: :)
#/ Options:
#/   --help: Display this help message
#/   --version: Display programm version
#/ Version: 0.1.0
usage() { grep '^#/' "$0" | cut -c4- ; exit 0 ; }
version() { grep '^#/ Version:' "$0" | cut -c13- ; exit 0 ; }
expr "$*" : ".*--help" > /dev/null && usage
expr "$*" : ".*--version" > /dev/null && version

set -e

source "$_DEVENV_ROOT/libs/ui.sh"
source "$_DEVENV_ROOT/libs/profile.sh"

email="edoardo.tenani@gmail.com"

# cleanup() {}

setup_email() {
	__devenv_ui_arrow "use email $email"
	if ! grep EMAIL "$profile_folder/envs" > /dev/null; then
		echo "EMAIL=$email" >> "$profile_folder/envs"
	fi
	__devenv_ui_ok
}

# Parse command line options.
# while getopts m: OPT; do
# 	case "$OPT" in
# 	m)
# 		email=$OPTARG
# 		;;
# 	\?)
# 		# getopts issues an error message
# 		usage
# 		exit 1
# 		;;
# 	esac
# done
# Remove the switches we parsed above.
shift "$((OPTIND - 1))"

profile_name=$1
profile_folder=$PROFILE_PATHS/$profile_name

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    # trap cleanup EXIT
    __devenv_ui_header "Creating profile '$profile_name'"

    __devenv_profile_create "$profile_name" "$profile_folder"

    profile_prepare_bin_folder "$profile_folder"
    profile_prepare_envs_file "$profile_folder"
    profile_prepare_aws_folder "$profile_folder"

    setup_email "$profile_folder"
    setup_ssh "$profile_folder"
    setup_aws "$profile_folder"

    devenv rehash "$profile_name"
    exit 0
fi
