#!/usr/bin/env bash
# provide devenv completions
set -e

source "$_DEVENV_ROOT/libs/ui.sh"
source "$_DEVENV_ROOT/libs/config.sh"
source "$_DEVENV_ROOT/libs/profile.sh"

if [ $1 = "--complete" ]; then
  exec ls $(get_config "profiles")/
  exit
fi

[ $# -eq 0 ] && __devenv_ui_abort "required argument: profile name"

profile=$1
profile_load_file="$(get_config "profiles")/$profile/load.sh"

if [ -e "$profile_load_file" ]; then
  "$profile_load_file"
else
  devenv rehash "$profile"
  "$profile_load_file"
fi

# echo "# END"
