#!/usr/bin/env bash
# Usage: devenv whoami
# Summary: Print current profile

set -e

source "$_DEVENV_ROOT/libs/profile.sh"

active_profile="$(__devenv_profile_get_active)"

if [[ "$active_profile" != "" ]]; then
  echo "$active_profile"
else
  if command -v cowsay > /dev/null 2&>1; then
    cowsay <<EOF
"Through others we become ourselves."
― Lev S. Vygotsky
EOF
  fi
  echo "No profile loaded"
fi
