#!/usr/bin/env bash
# Usage: devenv rehash
# Summary: Rebuild profiles loader and shims

set -e

# source $_DEVENV_ROOT/libs/vars.sh
source $_DEVENV_ROOT/libs/ui.sh
source $_DEVENV_ROOT/libs/profile.sh
source $_DEVENV_ROOT/libs/config.sh

[ $# -eq 0 ] && e_abort "required argument: profile name"

profile=$1
profile_exists $profile || e_abort "profile does not exists" 127

profile_load_file="$(get_config "profiles")/$profile/load.sh"
profile_run_file="$(get_config "profiles")/$profile/run.sh"

profile_loader=$(profile_generate_loader $profile)

# double quotes are mandatory
echo "$profile_loader" > $profile_load_file
echo 'export LP_PS1_PREFIX="$DEVENV_ACTIVE_PROFILE $LP_PS1_PREFIX"'  >> $profile_load_file
echo "$SHELL -l"  >> $profile_load_file
chmod 700 $profile_load_file

# double quotes are mandatory
echo "$profile_loader" > $profile_run_file
echo "eval \$@" >> $profile_run_file
chmod 700 $profile_run_file